# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField()),
                ('y', models.PositiveSmallIntegerField()),
                ('current_durability', models.PositiveIntegerField()),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('health', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('durability', models.IntegerField(default=30)),
                ('consumable', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='creature',
            new_name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ItemType'),
        ),
    ]
