# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160225_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='enemy_aggro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creature',
            name='enemy_damage',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
