# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160225_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='enemy_aggro',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='enemy_damage',
        ),
        migrations.AddField(
            model_name='creaturetype',
            name='enemy_aggro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creaturetype',
            name='enemy_damage',
            field=models.SmallIntegerField(default=0),
        ),
    ]
