# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160225_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('damage', models.IntegerField(default=0)),
                ('is_solid', models.BooleanField(default=True)),
                ('floor', models.BooleanField(default=True)),
            ],
        ),
    ]
