# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160225_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='creaturetype',
            name='symbol',
            field=models.CharField(default=' ', max_length=1),
            preserve_default=False,
        ),
    ]
