# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_creaturetype_symbol'),
        ('game', '0006_tiletype'),
    ]

    operations = [
    ]
