# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_character_sin_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.Level'),
        ),
        migrations.AlterField(
            model_name='creature',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.Level'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.Level'),
        ),
    ]
